version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-spring
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
